services:
  mysql:
    image: mysql:8.0
    container_name: modern-db-admin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sample_db
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres:
    image: postgres:16
    container_name: modern-db-admin-postgres
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: sample_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
